version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: mysql_eventmanager
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: event_manager
            MYSQL_USER: admin
            MYSQL_PASSWORD: jk9d88yn
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
